# Generated by Django 5.0.1 on 2024-10-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Stu_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Stu_Name', models.CharField(max_length=20)),
                ('Stu_Email', models.CharField(max_length=20)),
                ('Stu_Password', models.CharField(max_length=10)),
                ('Stu_Age', models.IntegerField()),
            ],
        ),
    ]
