# Generated by Django 5.0.1 on 2024-08-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Student_Username', models.CharField(max_length=20)),
                ('Student_Password', models.CharField(max_length=20)),
                ('Student_Firstname', models.CharField(max_length=20)),
                ('Student_Lastname', models.CharField(max_length=20)),
                ('Student_Age', models.IntegerField()),
                ('Student_Course', models.CharField(max_length=20)),
            ],
        ),
    ]
