# Generated by Django 5.0.1 on 2024-10-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('User_Name', models.CharField(max_length=20)),
                ('Email_ID', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=20)),
                ('Age', models.IntegerField(max_length=20)),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
