# Generated by Django 5.0.1 on 2024-08-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Faculty_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
