# Generated by Django 5.0.1 on 2024-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=20)),
                ('Student_Age', models.IntegerField()),
                ('Student_Stream', models.CharField(max_length=20)),
            ],
        ),
    ]
