# Generated by Django 5.0.1 on 2024-08-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peon',
            fields=[
                ('Peon_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Peon_Username', models.CharField(max_length=20)),
                ('Peon_Password', models.CharField(max_length=20)),
                ('Peon_Firstname', models.CharField(max_length=20)),
                ('Peon_Lastname', models.CharField(max_length=20)),
                ('Peon_Age', models.IntegerField()),
                ('Peon_Salary', models.IntegerField()),
                ('Peon_Contactno', models.IntegerField()),
            ],
        ),
    ]
