# Generated by Django 5.0.1 on 2024-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=30)),
                ('Student_Age', models.IntegerField()),
                ('Student_Email', models.EmailField(max_length=50)),
                ('Student_City', models.CharField(max_length=20)),
            ],
        ),
    ]
